jobs:
  SAST-CodeQL:
    name: Build, Test, and SAST CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

      - name: Build project using Maven
        run: mvn clean install

      - name: Run tests with Maven
        run: mvn test

      - name: Create binary directory
        run: mkdir candidate-binary && cp target/*.jar candidate-binary

      - name: Copying test results
        run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results

      - name: Upload Application Binary
        uses: actions/upload-artifact@v4
        with:
          name: Application-Binary
          path: candidate-binary

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: Test-Results
          path: test-results

      - name: Cleanup CodeQL database
        run: rm -rf ${{ github.workspace }}/codeql-database

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
