name: CodeQL SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly

jobs:
  build:
    name: Build Java application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project using Maven
        run: mvn clean install

      - name: Test with Maven
        run: mvn test
      - run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results

      
