name: CodeQL SAST Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1'  # Run weekly

jobs:
  build:
    name: Build Java application
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        language: ['java']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Build project using Maven
        run: mvn clean install
      - run: mkdir candidate-binary && cp target/*.jar candidate-binary

      - name: Test with Maven
        run: mvn test

      - name: Copying test results
        run: mkdir test-results && cp target/*-reports/TEST-*.xml test-results

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Application-Binary
          path: candidate-binary

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Test-Results
          path: test-results

      # CodeQL Analysis Steps
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{ matrix.language }}"
        
      



      
